# .github/workflows/download_jmcomic.yml
name: Download JMComic Album

on:
  workflow_dispatch:
    inputs:
      album_id:
        description: 'Album ID to download'
        required: true
        type: string
jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install jmcomic img2pdf && pip install psutil

    - name: mkdir 
      run: |
        mkdir /tmp/pdf
    - name: Run download script
      run: |
        python jm.py ${{ github.event.inputs.album_id }} option.yml
    - name: Set up rclone
      uses: AnimMouse/setup-rclone@v1    
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}
    - name: mv file
      run: |
        rclone copy --ignore-existing --progress /tmp/pdf/${{ github.event.inputs.album_id }}.pdf onedrive:PDF/
